version: '2'
services:
  #  datagen:
  #    image: chris/datagen
  #    depends_on:
  #      - kafka
  #    command: "java -classpath /opt/datagen/flink-sql-demo.jar myflink.SourceGenerator --input /opt/datagen/user_behavior.log --output kafka kafka:9092 --speedup 2000"
  #    environment:
  #      ZOOKEEPER_CONNECT: zookeeper
  #      KAFKA_BOOTSTRAP: kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  minio1:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    user: ${LOCAL_USER_ID}:${LOCAL_GROUP_ID}
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - ${HOME}/minio/data:/data
    command: server /data --console-address ":9001"
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9094:9094
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./docker_data:/var/lib/mysqla
    user: mysql
  memcached-server:
    image: memcached
    ports:
      - 11211:11211
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  hitorro-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/chris/docker_data
