# H2 Database Configuration
#spring.datasource.url=jdbc:h2:mem:questionnaire
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#
## JPA Configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring:
    application:
        name: questionaire

    sql:
        init:
            mode: always

    # Database configuration
    datasource:
        url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:questionare}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: ${DB_USERNAME:questionare}
        password: ${DB_PASSWORD:123456}
        driver-class-name: com.mysql.cj.jdbc.Driver

# JPA configuration
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
   #             format_sql: true
        show-sql: ${SHOW_SQL:false}
   #     defer-datasource-initialization: true

# Server Configuration
server:
    port: 8080



